name: dixbase_sdk
description: SDK no oficial para la pasarela de pagos Dixbase (https://dixbase.com). Permite crear facturas, consultar criptomonedas y gestionar negocios.
version: 1.0.0
repository: https://github.com/acano99/dixbase_sdk 
homepage: https://github.com/acano99/dixbase_sdk
issue_tracker: https://github.com/acano99/dixbase_sdk/issues

environment:
  sdk: ^3.11.4

dependencies:
  http: ^1.6.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6